# Configura??es do Telegram Bot
telegram.bot.token=
telegram.chat.id=

# Configura??es de scraping
scraping.user.agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
scraping.timeout=30000
